# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=4.0.0@sha256:eec957fb65cbd367c6a61a388d5db14e4f1f86cda0488a5185a3e8d2ba5d93b6
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
