# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=4.0.1@sha256:12a310c7b6a14bb0dd45a1032748ada9d2baacb60944189447a87e85318d5fc3
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
