# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.7@sha256:5ca3f3c0be2e78f1920b1b0f40c82aaafd4ed2ca0201b622ebc661b1bfce3c4e
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
